// Date: 7/10/2014 10:33:29 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.hakrismod;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class LavaCanM extends ModelBase
{
  //fields
    ModelRenderer Base;
    ModelRenderer Shape1;
    ModelRenderer Shape99;
    ModelRenderer lrop;
    ModelRenderer derp;
  
  public LavaCanM()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      Base = new ModelRenderer(this, 0, 0);
      Base.addBox(0F, 0F, 0F, 8, 8, 1);
      Base.setRotationPoint(-2F, 15F, 0F);
      Base.setTextureSize(64, 32);
      Base.mirror = true;
      setRotation(Base, -1.570796F, 0F, 0F);
      Shape1 = new ModelRenderer(this, 0, 10);
      Shape1.addBox(0F, 0F, 0F, 8, 8, 1);
      Shape1.setRotationPoint(-2F, 8F, 0F);
      Shape1.setTextureSize(64, 32);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0F, 0F);
      Shape99 = new ModelRenderer(this, 37, 0);
      Shape99.addBox(0F, 0F, 0F, 7, 8, 1);
      Shape99.setRotationPoint(-2F, 7F, -8F);
      Shape99.setTextureSize(64, 32);
      Shape99.mirror = true;
      setRotation(Shape99, 0F, 0F, 0F);
      lrop = new ModelRenderer(this, 0, 23);
      lrop.addBox(0F, 0F, 0F, 7, 7, 1);
      lrop.setRotationPoint(-1F, 8F, -7F);
      lrop.setTextureSize(64, 32);
      lrop.mirror = true;
      setRotation(lrop, 0F, -1.58825F, 0F);
      derp = new ModelRenderer(this, 19, 0);
      derp.addBox(0F, 0F, 0F, 7, 7, 1);
      derp.setRotationPoint(6F, 8F, -7F);
      derp.setTextureSize(64, 32);
      derp.mirror = true;
      setRotation(derp, 0F, -1.58825F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Base.render(f5);
    Shape1.render(f5);
    Shape99.render(f5);
    lrop.render(f5);
    derp.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5,Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }
public void  RenderLol(float zed) {
	 Base.render(zed);
	    Shape1.render(zed);
	    Shape99.render(zed);
	    lrop.render(zed);
	    derp.render(zed);
}
}
